import Header from "@/components/Header";
import Patient from "@/components/Patient";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";

function patient() {
  const router = useRouter();
  const [persons, setPersons] = useState(null);
  const [patient, setPatient] = useState("");
  useEffect(() => {
    const fetchName = async () => {
      if (router.isReady) {
        const { patient } = router.query;
        console.log(patient);
        const resp = await fetch(
          `https://patient-analysis.arasharora.repl.co/illness/?user_id=${patient}`
        );
        const data = await resp.json();
        setPatient(patient);
        setPersons(data);
      }
    };
    fetchName();
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-7xl px-20 mx-auto min-h-screen flex justify-center flex-wrap gap-16 items-center my-[60px]">
        {persons && <Patient patientdata={persons} />}
      </main>
    </>
  );
}

export default patient;
